workflows:
  ios-workflow:
    name: iOS Free Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd flutter_app_template
          flutter pub get
      - name: Build iOS
        script: |
          cd flutter_app_template
          flutter build ios --release --no-codesign
    artifacts:
      - flutter_app_template/build/ios/iphoneos/Runner.app
