workflows:
  ios-workflow:
    name: iOS Free Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd flutter_app_template
          flutter pub get
      - name: Build iOS
        script: |
          cd flutter_app_template
          flutter build ios --release --no-codesign
          
          # Convert .app to .ipa for direct download
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r -q app.ipa Payload
    artifacts:
      - flutter_app_template/build/ios/iphoneos/app.ipa
